name: NASA Project CI #para dar nombre al workflow
on: #para indicar en que evento se activa el workflow
  push: #para indicar que el workflow se active en un push
    branches: [master] #el workflow se activa cuando se haga push a la rama master
  pull_request: #para indicar que el workflow se active en un pull_request
    branches: [master] #el workflow se activa cuando se haga pull_request a la rama master
jobs: #los workflows se componen de uno o mas jobs
  build: #lo primero que hace el job es el build
    runs-on: ubuntu-latest #indica en que plataformas se puede ejecutar el job
    steps: #indica los pasos de jobs.
      - uses: actions/checkout@v2 #las acciones a usar por el job. Esta es una action reutilizaboe de github
      - name: Use Node.js version 16 #podemos darle nombre a los pasos
        uses: actions/setup-node@v2
        with: #para indicar algun parametro de la acción
          node-version: '16' #en este caso el parametro es la version de node
      - run: npm install #para correr nuestros propios comandos
      - run: npm run build --prefix client
