name: NASA Project CI #para dar nombre al workflow
on: #para indicar en que evento se activa el workflow
  push: #para indicar que el workflow se active en un push
    branches: [master] #el workflow se activa cuando se haga push a la rama master
  pull_request: #para indicar que el workflow se active en un pull_request
    branches: [master] #el workflow se activa cuando se haga pull_request a la rama master
jobs: #los workflows se componen de uno o mas jobs
  build: #lo primero que hace el job es el build
    env: #para especificar el ambiente en el que correrá el job
      CI: true #caracteristica propia del script test de create react app
      MONGO_URL: mongodb://localhost/nasa #configuramos una varible de ambiente que usara el servidor de mongo que se crea para las pruebas en CI
    strategy: #para establecer otras configuraciones para el job como diferentes variables de ambiente o versiones de node. Esto ocasionara que haya un job build corriendo en paralelo por cada variable
      matrix: #para establecer arreglos de variables
        node-version: [14.x, 16.x] #en este caso establezco variables de versiones de node. Por tener 2 variables habran 2 procesos corriendo en paralelo.
        mongodb-version: ['4.4'] #para hacer pruebas en versiones de mongodb. como solo tengo una variable no afecta la cantidad de procesos a correr ya que los 2 existente usaran esta misma version de mongodb
    runs-on: ubuntu-latest #indica en que plataformas se puede ejecutar el job
    steps: #indica los pasos de jobs.
      - uses: actions/checkout@v2 #las acciones a usar por el job. Esta es una action reutilizaboe de github
      - name: Use Node.js version ${{ matrix.node-version }} #podemos darle nombre a los pasos
        uses: actions/setup-node@v2
        with: #para indicar algun parametro de la acción
          node-version: ${{ matrix.node-version }} #en este caso el parametro es la version de node que se para como parametro que se toma de la matriz
      - name: User MongoDB from GitHub Actions
        uses: supercharge/mongodb-github-action@1.7.0 #https://github.com/marketplace/actions/mongodb-in-github-actions
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install #para correr nuestros propios comandos
      - run: npm run build --prefix client
      - run: npm test #script del package.json para ejecutar los tests del frontend y backend
